name: storybot_app
description: Eğitici hikayeler sunan mobil uygulama.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Durum Yönetimi
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigasyon
  go_router: ^13.0.1

  # HTTP ve API
  dio: ^5.4.0
  retrofit: ^4.0.3

  # Yerel Depolama
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # UI Bileşenleri
  cupertino_icons: ^1.0.6
  flutter_markdown: ^0.6.18
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9

  # Ses İşleme
  just_audio: ^0.9.36
  audio_session: ^0.1.18

  # Validasyon
  form_field_validator: ^1.1.0

  # Yardımcı Paketler
  intl: ^0.18.1
  path_provider: ^2.1.1
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.2
  device_info_plus: ^9.1.1
  connectivity_plus: ^5.0.2
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Geliştirici Araçları
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  riverpod_generator: ^2.3.9
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash_android12.png
    color: "#FFFFFF"
  fullscreen: true